name: Apply

on:
  pull_request:
    branches:
    - master
    types:
    - closed
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Get PR Number
        id: pr_number
        run: echo "PR Number is ${{ github.event.pull_request.number }}"
          
      - name: list files
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"`
          FILES=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '.[] | .filename')
          echo changed_files=$FILES >> $GITHUB_ENV
        shell: bash

      - name: Run Script on Desired Value
        run: |
          chmod +x ./.github/scripts/test.sh
          ./.github/scripts/test.sh \
          --changed_files "${{ env.changed_files }}"
        shell: bash
