name: Apply

on:
  pull_request:
    branches:
    - master
    types:
    - closed
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Get Pull Request Number
        run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash

      - name: print pr number
        run: echo "The Pull Request SHA is ${{ env.PULL_NUMBER }}"
