name: Apply

on:
  pull_request:
    branches:
    - master
    types:
    - closed
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print SHA
        run: echo "The Pull Request SHA is ${{ github.event.pull_request.head.sha }}"
