name: Terraform Infra

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: validate the values
        run: |
          echo 'github.event_name: ${{ github.event_name }}'
          echo 'github.event.action: ${{ github.event.action }}'
          echo 'github.event.pull_request.number: ${{ github.event.pull_request.number }}'
          echo 'github.event.pull_request.merged: ${{ github.event.pull_request.merged }}'
          echo 'github.repository: ${{ github.repository }}'
          echo 'github.event.repository.url: ${{ github.event.repository.url }}'
