name: Terraform Infra
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch.
  push:
    branches:
    - master
    
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      

    - name: list files
      id: changes
      if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && contains ( github.event.head_commit.message == 'Merge pull request' )
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo $FILES

          
