name: demo
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch.
  push:
    branches: [ "final" ]
  pull_request:
    branches: [ "final" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 0
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: changes
        run: |
          # Diff HEAD with the previous commit
          #$diff = git diff --name-only HEAD^ HEAD
          $diff = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          
          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          #$SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
          #$HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docs_changed"
          #Write-Host "::set-output name=docs_changed::$HasDiff"
          run: echo "docs_changed=$HasDiff" >>$GITHUB_OUTPUT

          
