name: Terraform Infra

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: list files
        if: ( github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true )
        #if: ${{ github.ref == 'refs/heads/master' && contains ( github.event.head_commit.message == 'Merge pull request' ) }}
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
